cat /media/sf_Astro/k_cat/single_e_w/N01_ew_cat.dat /media/sf_Astro/k_cat/single_w_e/N01_we_cat.dat | sort | uniq > /media/sf_Astro/k_cat/single_canon/N01_all.dat
cat /media/sf_Astro/k_cat/single_e_w/N02_ew_cat.dat /media/sf_Astro/k_cat/single_w_e/N02_we_cat.dat | sort | uniq > /media/sf_Astro/k_cat/single_canon/N02_all.dat
cat /media/sf_Astro/k_cat/single_e_w/N03_ew_cat.dat /media/sf_Astro/k_cat/single_w_e/N03_we_cat.dat | sort | uniq > /media/sf_Astro/k_cat/single_canon/N03_all.dat
cat /media/sf_Astro/k_cat/single_e_w/N04_ew_cat.dat /media/sf_Astro/k_cat/single_w_e/N04_we_cat.dat | sort | uniq > /media/sf_Astro/k_cat/single_canon/N04_all.dat
cat /media/sf_Astro/k_cat/single_e_w/N05_ew_cat.dat /media/sf_Astro/k_cat/single_w_e/N05_we_cat.dat | sort | uniq > /media/sf_Astro/k_cat/single_canon/N05_all.dat
cat /media/sf_Astro/k_cat/single_e_w/N06_ew_cat.dat /media/sf_Astro/k_cat/single_w_e/N06_we_cat.dat | sort | uniq > /media/sf_Astro/k_cat/single_canon/N06_all.dat
cat /media/sf_Astro/k_cat/single_e_w/N07_ew_cat.dat /media/sf_Astro/k_cat/single_w_e/N07_we_cat.dat | sort | uniq > /media/sf_Astro/k_cat/single_canon/N07_all.dat
cat /media/sf_Astro/k_cat/single_e_w/N08_ew_cat.dat /media/sf_Astro/k_cat/single_w_e/N08_we_cat.dat | sort | uniq > /media/sf_Astro/k_cat/single_canon/N08_all.dat
cat /media/sf_Astro/k_cat/single_e_w/N09_ew_cat.dat /media/sf_Astro/k_cat/single_w_e/N09_we_cat.dat | sort | uniq > /media/sf_Astro/k_cat/single_canon/N09_all.dat
cat /media/sf_Astro/k_cat/single_e_w/N10_ew_cat.dat /media/sf_Astro/k_cat/single_w_e/N10_we_cat.dat | sort | uniq > /media/sf_Astro/k_cat/single_canon/N10_all.dat
cat /media/sf_Astro/k_cat/single_e_w/N11_ew_cat.dat /media/sf_Astro/k_cat/single_w_e/N11_we_cat.dat | sort | uniq > /media/sf_Astro/k_cat/single_canon/N11_all.dat
cat /media/sf_Astro/k_cat/single_e_w/N12_ew_cat.dat /media/sf_Astro/k_cat/single_w_e/N12_we_cat.dat | sort | uniq > /media/sf_Astro/k_cat/single_canon/N12_all.dat
cat /media/sf_Astro/k_cat/single_e_w/N13_ew_cat.dat /media/sf_Astro/k_cat/single_w_e/N13_we_cat.dat | sort | uniq > /media/sf_Astro/k_cat/single_canon/N13_all.dat
cat /media/sf_Astro/k_cat/single_e_w/S19_ew_cat.dat /media/sf_Astro/k_cat/single_w_e/S19_we_cat.dat | sort | uniq > /media/sf_Astro/k_cat/single_canon/S19_all.dat
cat /media/sf_Astro/k_cat/single_e_w/S20_ew_cat.dat /media/sf_Astro/k_cat/single_w_e/S20_we_cat.dat | sort | uniq > /media/sf_Astro/k_cat/single_canon/S20_all.dat
cat /media/sf_Astro/k_cat/single_e_w/S22_ew_cat.dat /media/sf_Astro/k_cat/single_w_e/S22_we_cat.dat | sort | uniq > /media/sf_Astro/k_cat/single_canon/S22_all.dat
cat /media/sf_Astro/k_cat/single_e_w/S23_ew_cat.dat /media/sf_Astro/k_cat/single_w_e/S23_we_cat.dat | sort | uniq > /media/sf_Astro/k_cat/single_canon/S23_all.dat
cat /media/sf_Astro/k_cat/single_e_w/S24_ew_cat.dat /media/sf_Astro/k_cat/single_w_e/S24_we_cat.dat | sort | uniq > /media/sf_Astro/k_cat/single_canon/S24_all.dat
cat /media/sf_Astro/k_cat/single_e_w/S25_ew_cat.dat /media/sf_Astro/k_cat/single_w_e/S25_we_cat.dat | sort | uniq > /media/sf_Astro/k_cat/single_canon/S25_all.dat
cat /media/sf_Astro/k_cat/single_e_w/S26_ew_cat.dat /media/sf_Astro/k_cat/single_w_e/S26_we_cat.dat | sort | uniq > /media/sf_Astro/k_cat/single_canon/S26_all.dat
cat /media/sf_Astro/k_cat/single_e_w/S27_ew_cat.dat /media/sf_Astro/k_cat/single_w_e/S27_we_cat.dat | sort | uniq > /media/sf_Astro/k_cat/single_canon/S27_all.dat
cat /media/sf_Astro/k_cat/single_e_w/S28_ew_cat.dat /media/sf_Astro/k_cat/single_w_e/S28_we_cat.dat | sort | uniq > /media/sf_Astro/k_cat/single_canon/S28_all.dat
