sort /media/sf_Astro/k_cat/sed_remove/sed_removeN01 | uniq > /media/sf_Astro/k_cat/sed_r_u/N01
sort /media/sf_Astro/k_cat/sed_remove/sed_removeN02 | uniq > /media/sf_Astro/k_cat/sed_r_u/N02
sort /media/sf_Astro/k_cat/sed_remove/sed_removeN03 | uniq > /media/sf_Astro/k_cat/sed_r_u/N03
sort /media/sf_Astro/k_cat/sed_remove/sed_removeN04 | uniq > /media/sf_Astro/k_cat/sed_r_u/N04
sort /media/sf_Astro/k_cat/sed_remove/sed_removeN05 | uniq > /media/sf_Astro/k_cat/sed_r_u/N05
sort /media/sf_Astro/k_cat/sed_remove/sed_removeN06 | uniq > /media/sf_Astro/k_cat/sed_r_u/N06
sort /media/sf_Astro/k_cat/sed_remove/sed_removeN07 | uniq > /media/sf_Astro/k_cat/sed_r_u/N07
sort /media/sf_Astro/k_cat/sed_remove/sed_removeN08 | uniq > /media/sf_Astro/k_cat/sed_r_u/N08
sort /media/sf_Astro/k_cat/sed_remove/sed_removeN09 | uniq > /media/sf_Astro/k_cat/sed_r_u/N09
sort /media/sf_Astro/k_cat/sed_remove/sed_removeN10 | uniq > /media/sf_Astro/k_cat/sed_r_u/N10
sort /media/sf_Astro/k_cat/sed_remove/sed_removeN11 | uniq > /media/sf_Astro/k_cat/sed_r_u/N11
sort /media/sf_Astro/k_cat/sed_remove/sed_removeN12 | uniq > /media/sf_Astro/k_cat/sed_r_u/N12
sort /media/sf_Astro/k_cat/sed_remove/sed_removeN13 | uniq > /media/sf_Astro/k_cat/sed_r_u/N13
sort /media/sf_Astro/k_cat/sed_remove/sed_removeS19 | uniq > /media/sf_Astro/k_cat/sed_r_u/S19
sort /media/sf_Astro/k_cat/sed_remove/sed_removeS20 | uniq > /media/sf_Astro/k_cat/sed_r_u/S20
sort /media/sf_Astro/k_cat/sed_remove/sed_removeS22 | uniq > /media/sf_Astro/k_cat/sed_r_u/S22
sort /media/sf_Astro/k_cat/sed_remove/sed_removeS23 | uniq > /media/sf_Astro/k_cat/sed_r_u/S23
sort /media/sf_Astro/k_cat/sed_remove/sed_removeS24 | uniq > /media/sf_Astro/k_cat/sed_r_u/S24
sort /media/sf_Astro/k_cat/sed_remove/sed_removeS25 | uniq > /media/sf_Astro/k_cat/sed_r_u/S25
sort /media/sf_Astro/k_cat/sed_remove/sed_removeS26 | uniq > /media/sf_Astro/k_cat/sed_r_u/S26
sort /media/sf_Astro/k_cat/sed_remove/sed_removeS27 | uniq > /media/sf_Astro/k_cat/sed_r_u/S27
sort /media/sf_Astro/k_cat/sed_remove/sed_removeS28 | uniq > /media/sf_Astro/k_cat/sed_r_u/S28
