sort /media/sf_Astro/k_cat/single_all/N01_all.dat | uniq > /media/sf_Astro/k_cat/single_canon/N01_all.dat
sort /media/sf_Astro/k_cat/single_all/N02_all.dat | uniq > /media/sf_Astro/k_cat/single_canon/N02_all.dat
sort /media/sf_Astro/k_cat/single_all/N03_all.dat | uniq > /media/sf_Astro/k_cat/single_canon/N03_all.dat
sort /media/sf_Astro/k_cat/single_all/N04_all.dat | uniq > /media/sf_Astro/k_cat/single_canon/N04_all.dat
sort /media/sf_Astro/k_cat/single_all/N05_all.dat | uniq > /media/sf_Astro/k_cat/single_canon/N05_all.dat
sort /media/sf_Astro/k_cat/single_all/N06_all.dat | uniq > /media/sf_Astro/k_cat/single_canon/N06_all.dat
sort /media/sf_Astro/k_cat/single_all/N07_all.dat | uniq > /media/sf_Astro/k_cat/single_canon/N07_all.dat
sort /media/sf_Astro/k_cat/single_all/N08_all.dat | uniq > /media/sf_Astro/k_cat/single_canon/N08_all.dat
sort /media/sf_Astro/k_cat/single_all/N09_all.dat | uniq > /media/sf_Astro/k_cat/single_canon/N09_all.dat
sort /media/sf_Astro/k_cat/single_all/N10_all.dat | uniq > /media/sf_Astro/k_cat/single_canon/N10_all.dat
sort /media/sf_Astro/k_cat/single_all/N11_all.dat | uniq > /media/sf_Astro/k_cat/single_canon/N11_all.dat
sort /media/sf_Astro/k_cat/single_all/N12_all.dat | uniq > /media/sf_Astro/k_cat/single_canon/N12_all.dat
sort /media/sf_Astro/k_cat/single_all/N13_all.dat | uniq > /media/sf_Astro/k_cat/single_canon/N13_all.dat
sort /media/sf_Astro/k_cat/single_all/S19_all.dat | uniq > /media/sf_Astro/k_cat/single_canon/S19_all.dat
sort /media/sf_Astro/k_cat/single_all/S20_all.dat | uniq > /media/sf_Astro/k_cat/single_canon/S20_all.dat
sort /media/sf_Astro/k_cat/single_all/S22_all.dat | uniq > /media/sf_Astro/k_cat/single_canon/S22_all.dat
sort /media/sf_Astro/k_cat/single_all/S23_all.dat | uniq > /media/sf_Astro/k_cat/single_canon/S23_all.dat
sort /media/sf_Astro/k_cat/single_all/S24_all.dat | uniq > /media/sf_Astro/k_cat/single_canon/S24_all.dat
sort /media/sf_Astro/k_cat/single_all/S25_all.dat | uniq > /media/sf_Astro/k_cat/single_canon/S25_all.dat
sort /media/sf_Astro/k_cat/single_all/S26_all.dat | uniq > /media/sf_Astro/k_cat/single_canon/S26_all.dat
sort /media/sf_Astro/k_cat/single_all/S27_all.dat | uniq > /media/sf_Astro/k_cat/single_canon/S27_all.dat
sort /media/sf_Astro/k_cat/single_all/S28_all.dat | uniq > /media/sf_Astro/k_cat/single_canon/S28_all.dat
